/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_malteharms_libmi_Native */

#ifndef _Included_de_malteharms_libmi_Native
#define _Included_de_malteharms_libmi_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_malteharms_libmi_Native
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_de_malteharms_libmi_Native_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    decrypt
 * Signature: ([Ljava/lang/Byte;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_malteharms_libmi_Native_decrypt
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    sha256
 * Signature: (Ljava/lang/String;)[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_de_malteharms_libmi_Native_sha256
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    generateKeyPair
 * Signature: ()[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_de_malteharms_libmi_Native_generateKeyPair
  (JNIEnv *, jclass);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    calculateECDHE
 * Signature: ([Ljava/lang/Byte;[Ljava/lang/Byte;)[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_de_malteharms_libmi_Native_calculateECDHE
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
