/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_malteharms_libmi_Native */

#ifndef _Included_de_malteharms_libmi_Native
#define _Included_de_malteharms_libmi_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_malteharms_libmi_Native
 * Method:    encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_malteharms_libmi_Native_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_malteharms_libmi_Native_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    sha256
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_malteharms_libmi_Native_sha256
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    generateKeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_malteharms_libmi_Native_generateKeyPair
  (JNIEnv *, jclass);

/*
 * Class:     de_malteharms_libmi_Native
 * Method:    calculateECDHE
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_malteharms_libmi_Native_calculateECDHE
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
